[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
